{
  description =
    "Marquee - Kubernetes-ready ClojureScript UI service for Pseudovision/Tunarr ecosystem";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";

    # clj-nix packages Clojure/ClojureScript Maven dependencies for Nix and
    # generates the deps-lock.json used to build offline.
    clj-nix = {
      url = "github:jlesquembre/clj-nix/0.4.0";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Kept for later use (building/pushing Docker images). Not used by the
    # build/run/update outputs below yet.
    nix-helpers = {
      url = "github:fudoniten/fudo-nix-helpers";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, clj-nix, nix-helpers }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages."${system}";
        clj-pkgs = clj-nix.packages."${system}";

        nodejs = pkgs.nodejs_22;

        # JDK used to run shadow-cljs (the ClojureScript compiler) at build time.
        jdk = pkgs.jdk17_headless;
        clojure = pkgs.clojure.override { jdk = jdk; };

        # Offline Maven/git cache built from deps-lock.json (Maven side: shadow-cljs,
        # reagent, re-frame, ...). Generated by `nix run .#update`.
        deps-cache = clj-pkgs.mk-deps-cache { lockfile = ./deps-lock.json; };

        # npm dependencies (react, clsx, tailwind, ...) resolved from
        # package-lock.json without an extra fixed-output hash to maintain.
        node-modules = pkgs.importNpmLock.buildNodeModules {
          npmRoot = ./.;
          inherit nodejs;
        };

        # Build the static site:
        #   1. shadow-cljs release -> public/js/main.js
        #   2. tailwind -> public/css/main.css
        # then assemble public/ into $out.
        site = pkgs.stdenv.mkDerivation {
          pname = "marquee";
          version = "0.1.0";
          src = ./.;

          nativeBuildInputs = [ clojure jdk nodejs ];

          buildPhase = ''
            runHook preBuild

            # Point the Clojure CLI at the offline Maven cache (see clj-nix mkCljBin).
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"
            export JAVA_TOOL_OPTIONS="-Duser.home=${deps-cache}"
            export CLJ_CONFIG="${deps-cache}/.clojure"
            export CLJ_CACHE="$TMPDIR/cp_cache"
            export GITLIBS="${deps-cache}/.gitlibs"

            # npm packages for the JS interop (react, clsx, tailwind-merge, ...).
            ln -s ${node-modules}/node_modules node_modules

            # Compile ClojureScript (advanced optimizations via :release).
            clojure -M -m shadow.cljs.devtools.cli release app

            # Compile Tailwind, pulling classes from the cljs sources + index.html.
            ./node_modules/.bin/tailwindcss \
              -c tailwind.config.js \
              -i src/css/main.css \
              -o public/css/main.css \
              --minify

            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall
            mkdir -p $out
            cp -r public/. $out/
            runHook postInstall
          '';
        };

        # `nix run` -> serve the built site over HTTP.
        serve = pkgs.writeShellApplication {
          name = "marquee";
          runtimeInputs = [ pkgs.darkhttpd ];
          text = ''
            PORT="''${PORT:-8080}"
            echo "Serving marquee on http://localhost:$PORT"
            exec darkhttpd "${site}" --port "$PORT"
          '';
        };

        # `nix run .#update` -> regenerate both lockfiles from their manifests:
        #   - deps-lock.json   from deps.edn      (Maven, via clj-nix)
        #   - package-lock.json from package.json (npm)
        update = pkgs.writeShellApplication {
          name = "update";
          runtimeInputs = [ clj-pkgs.deps-lock nodejs ];
          text = ''
            cd "''${1:-$PWD}"
            echo "Regenerating deps-lock.json from deps.edn ..."
            deps-lock
            echo "Regenerating package-lock.json from package.json ..."
            npm install --package-lock-only
            echo "Done."
          '';
        };

        # `nix run .#dev-server` -> run shadow-cljs watch for development.
        dev-server = pkgs.writeShellApplication {
          name = "dev-server";
          runtimeInputs = [ clojure jdk nodejs ];
          text = ''
            cd "''${1:-$PWD}"
            PORT="''${PORT:-8080}"
            echo "Starting shadow-cljs dev server on http://localhost:$PORT"
            echo "Press Ctrl+C to stop."
            npx shadow-cljs watch app
          '';
        };

      in {
        packages.default = site;
        packages.site = site;

        apps.default = {
          type = "app";
          program = "${serve}/bin/marquee";
        };
        apps.update = {
          type = "app";
          program = "${update}/bin/update";
        };
        apps.dev-server = {
          type = "app";
          program = "${dev-server}/bin/dev-server";
        };

        devShells.default = pkgs.mkShell {
          packages = [ clojure jdk nodejs clj-pkgs.deps-lock ];
        };
      });
}
