{
  description =
    "Marquee - Kubernetes-ready ClojureScript UI service for Pseudovision/Tunarr ecosystem";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";

    # clj-nix packages Clojure/ClojureScript Maven dependencies for Nix and
    # generates the deps-lock.json used to build offline.
    clj-nix = {
      url = "github:jlesquembre/clj-nix/0.4.0";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Kept for later use (building/pushing Docker images). Not used by the
    # build/run/update outputs below yet.
    nix-helpers = {
      url = "github:fudoniten/fudo-nix-helpers";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, clj-nix, nix-helpers }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages."${system}";
        clj-pkgs = clj-nix.packages."${system}";

        # JDK used to run the ClojureScript (Closure) compiler at build time.
        jdk = pkgs.jdk17_headless;
        clojure = pkgs.clojure.override { jdk = jdk; };

        # Offline Maven/git cache built from deps-lock.json. Generated by
        # `nix run .#update` (see below). Must exist before `nix build`.
        deps-cache = clj-pkgs.mk-deps-cache { lockfile = ./deps-lock.json; };

        # Build the static site: compile ClojureScript -> public/js/main.js and
        # assemble it alongside the static assets in public/.
        site = pkgs.stdenv.mkDerivation {
          pname = "marquee";
          version = "0.1.0";
          src = ./.;

          nativeBuildInputs = [ clojure jdk ];

          buildPhase = ''
            runHook preBuild

            # Point the Clojure CLI at the offline cache (see clj-nix mkCljBin).
            export HOME="${deps-cache}"
            export JAVA_TOOL_OPTIONS="-Duser.home=${deps-cache}"
            export CLJ_CONFIG="$HOME/.clojure"
            export CLJ_CACHE="$TMPDIR/cp_cache"
            export GITLIBS="$HOME/.gitlibs"

            clojure -M -m cljs.main \
              --optimizations advanced \
              --output-dir "$TMPDIR/cljs-out" \
              --output-to public/js/main.js \
              --compile marquee.core

            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall
            mkdir -p $out
            cp -r public/. $out/
            runHook postInstall
          '';
        };

        # `nix run` -> serve the built site over HTTP.
        serve = pkgs.writeShellApplication {
          name = "marquee";
          runtimeInputs = [ pkgs.darkhttpd ];
          text = ''
            PORT="''${PORT:-8080}"
            echo "Serving marquee on http://localhost:$PORT"
            exec darkhttpd "${site}" --port "$PORT"
          '';
        };

        # `nix run .#update` -> regenerate deps-lock.json from deps.edn.
        update = pkgs.writeShellApplication {
          name = "update";
          runtimeInputs = [ clj-pkgs.deps-lock ];
          text = ''
            cd "''${1:-$PWD}"
            echo "Regenerating deps-lock.json in $PWD ..."
            deps-lock
          '';
        };

      in {
        packages.default = site;
        packages.site = site;

        apps.default = {
          type = "app";
          program = "${serve}/bin/marquee";
        };
        apps.update = {
          type = "app";
          program = "${update}/bin/update";
        };

        devShells.default =
          pkgs.mkShell { packages = [ clojure jdk clj-pkgs.deps-lock ]; };
      });
}
