{
  description =
    "Marquee - Kubernetes-ready ClojureScript UI service for Pseudovision/Tunarr ecosystem";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";

    # clj-nix packages Clojure/ClojureScript Maven dependencies for Nix and
    # generates the deps-lock.json used to build offline.
    clj-nix = {
      url = "github:jlesquembre/clj-nix/0.4.0";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # `fudoniten/fudo-nix-helpers` provides `deployContainers` for building
    # and pushing OCI images (used by the `deployContainer` output below).
    nix-helpers = {
      url = "github:fudoniten/fudo-nix-helpers";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, clj-nix, nix-helpers }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages."${system}";
        clj-pkgs = clj-nix.packages."${system}";
        helpers = nix-helpers.legacyPackages."${system}";

        # Version information (git commit + timestamp)
        versionInfo = let
          gitCommit = self.rev or self.dirtyRev or "unknown";
          gitTimestamp = if self ? lastModified then
            let
              ts = toString self.lastModified;
              year = builtins.substring 0 4 ts;
              month = builtins.substring 4 2 ts;
              day = builtins.substring 6 2 ts;
            in "${year}${month}${day}"
          else
            "dev";
          versionTag = "${builtins.substring 0 7 gitCommit}-${gitTimestamp}";
        in { inherit gitCommit gitTimestamp versionTag; };

        nodejs = pkgs.nodejs_22;

        # JDK used to run shadow-cljs (the ClojureScript compiler) at build time.
        jdk = pkgs.jdk21_headless;
        clojure = pkgs.clojure.override { jdk = jdk; };

        # Offline Maven/git cache built from deps-lock.json (Maven side: shadow-cljs,
        # reagent, re-frame, ...). Generated by `nix run .#update`.
        deps-cache = clj-pkgs.mk-deps-cache { lockfile = ./deps-lock.json; };

        # npm dependencies (react, clsx, tailwind, ...) resolved from
        # package-lock.json without an extra fixed-output hash to maintain.
        node-modules = pkgs.importNpmLock.buildNodeModules {
          npmRoot = ./.;
          inherit nodejs;
        };

        # Build the static site:
        #   1. shadow-cljs release -> public/js/main.js
        #   2. tailwind -> public/css/main.css
        # then assemble public/ into $out.
        site = pkgs.stdenv.mkDerivation {
          pname = "marquee";
          version = "0.1.0";
          src = ./.;

          nativeBuildInputs = [ clojure jdk nodejs ];

          buildPhase = ''
            runHook preBuild

            # Point the Clojure CLI at the offline Maven cache (see clj-nix mkCljBin).
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"
            export JAVA_TOOL_OPTIONS="-Duser.home=${deps-cache}"
            export CLJ_CONFIG="${deps-cache}/.clojure"
            export CLJ_CACHE="$TMPDIR/cp_cache"
            export GITLIBS="${deps-cache}/.gitlibs"

            # npm packages for the JS interop (react, clsx, tailwind-merge, ...).
            ln -s ${node-modules}/node_modules node_modules

            # Compile ClojureScript (advanced optimizations via :release).
            clojure -M -m shadow.cljs.devtools.cli release app

            # Compile Tailwind, pulling classes from the cljs sources + index.html.
            ./node_modules/.bin/tailwindcss \
              -c tailwind.config.js \
              -i src/css/main.css \
              -o public/css/main.css \
              --minify

            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall
            mkdir -p $out
            cp -r public/. $out/
            runHook postInstall
          '';
        };

        # `nix run` -> serve the built site over HTTP.
        serve = pkgs.writeShellApplication {
          name = "marquee";
          runtimeInputs = [ pkgs.darkhttpd ];
          text = ''
            PORT="''${PORT:-8080}"
            echo "Serving marquee on http://localhost:$PORT"
            exec darkhttpd "${site}" --port "$PORT"
          '';
        };

        # `nix run .#update` -> regenerate both lockfiles from their manifests:
        #   - deps-lock.json   from deps.edn      (Maven, via clj-nix)
        #   - package-lock.json from package.json (npm)
        update = pkgs.writeShellApplication {
          name = "update";
          runtimeInputs = [ clj-pkgs.deps-lock nodejs ];
          text = ''
            cd "''${1:-$PWD}"
            echo "Regenerating deps-lock.json from deps.edn ..."
            deps-lock
            echo "Regenerating package-lock.json from package.json ..."
            npm install --package-lock-only
            echo "Done."
          '';
        };

        # `nix run .#dev-server` -> run shadow-cljs watch + BFF server for development.
        dev-server = pkgs.writeShellApplication {
          name = "dev-server";
          runtimeInputs = [ clojure jdk nodejs ];
          text = ''
            cd "''${1:-$PWD}"
            PORT="''${PORT:-8080}"
            BFF_PORT="''${BFF_PORT:-3000}"

            echo "Starting Marquee development environment..."
            echo "  Frontend (shadow-cljs): http://localhost:$PORT"
            echo "  BFF server:             http://localhost:$BFF_PORT"
            echo "Press Ctrl+C to stop all services."
            echo ""

            # Link Nix-managed node_modules so shadow-cljs can find react etc.
            if [ ! -e node_modules ]; then
              ln -s ${node-modules}/node_modules node_modules
            fi

            mkdir -p public/css

            # Initial synchronous build so the file exists before the HTTP server
            # starts serving requests (shadow-cljs opens its HTTP port immediately).
            ./node_modules/.bin/tailwindcss \
              -c tailwind.config.js \
              -i src/css/main.css \
              -o public/css/main.css

            # Kill all background jobs on exit
            trap 'kill $(jobs -p) 2>/dev/null' EXIT

            # Start Tailwind CSS watcher in background
            ./node_modules/.bin/tailwindcss \
              -c tailwind.config.js \
              -i src/css/main.css \
              -o public/css/main.css \
              --watch &

            # Start BFF server in background
            echo "Starting BFF server on port $BFF_PORT..."
            clojure -M:server &

            # Wait a moment for BFF to start
            sleep 2

            # Start shadow-cljs in foreground (this will block until Ctrl+C)
            echo "Starting shadow-cljs on port $PORT..."
            npx shadow-cljs watch app
          '';
        };

        # Source tree passed to `mkClojureBin` for the BFF uberjar.
        # Mirrors the project source and adds the SPA assets produced by the
        # `site` derivation under `resources/public/`. Because `resources` is
        # on `:paths` (see deps.edn), clj-nix's uberjar builder copies it into
        # the jar, so the compiled index.html/JS/CSS are available on the
        # classpath under `public/` for `io/resource` / `wrap-resource`.
        bffSrc = pkgs.stdenv.mkDerivation {
          name = "marquee-bff-src";
          phases = [ "buildPhase" "installPhase" ];
          # Stage everything into the writable build directory first; the
          # install phase then promotes the finished layout into $out so the
          # intermediate store path is never written to read-only.
          buildPhase = ''
            runHook preBuild
            cp -rp ${./.}/. .
            chmod -R u+w .
            # `marquee.server.dev` is a shadow-cljs dev-only proxy predicate
            # that imports a shadow class; it is not part of the BFF and must
            # not be AOT-compiled into the uberjar, so drop it from the build.
            rm -f src/marquee/server/dev.clj
            # Embed the compiled SPA as classpath resources under `public/`.
            mkdir -p resources/public
            cp -rLp ${site}/. resources/public/
            runHook postBuild
          '';
          installPhase = ''
            runHook preInstall
            mkdir -p $out
            install -m 0755 -d $out
            cp -rp . $out/
            runHook postInstall
          '';
        };

      in {
        packages.default = site;
        packages.site = site;

        # Runnable BFF: a Clojure uberjar that AOT-compiles
        # `marquee.server.core` and embeds the compiled SPA at `public/`.
        packages.bff = helpers.mkClojureBin {
          name = "org.fudo/marquee-server";
          primaryNamespace = "marquee.server.core";
          src = bffSrc;
        };

        packages.deployContainer = let version = versionInfo;
        in helpers.deployContainers {
          name = "marquee";
          repo = "registry.kube.sea.fudo.link";
          tags = [ "latest" version.versionTag ];
          env = {
            GIT_COMMIT = version.gitCommit;
            GIT_TIMESTAMP = version.gitTimestamp;
            VERSION = version.versionTag;
          };
          entrypoint = [ "${self.packages."${system}".bff}/bin/marquee-server" ];
          verbose = true;
        };

        apps.default = {
          type = "app";
          program = "${serve}/bin/marquee";
        };
        apps.deployContainer = {
          type = "app";
          program = "${
              self.packages."${system}".deployContainer
            }/bin/deployContainers";
        };
        apps.update = {
          type = "app";
          program = "${update}/bin/update";
        };
        apps.dev-server = {
          type = "app";
          program = "${dev-server}/bin/dev-server";
        };

        devShells.default = pkgs.mkShell {
          packages = [ clojure jdk nodejs clj-pkgs.deps-lock ];
        };
      });
}
